server:
  port: 8082

spring:
  application:
    name: watermark-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:192.168.70.197:8848}
        namespace: ${NACOS_NAMESPACE:public}
      config:
        server-addr: ${NACOS_SERVER:192.168.70.197:8848}
        namespace: ${NACOS_NAMESPACE:public}
        file-extension: yml
        refresh-enabled: true
        import-check:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.dataplatform.watermark: DEBUG
