server:
  port: 8080

spring:
  application:
    name: desensitization-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      config:
        enabled: true
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
